import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "./components/Header";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={rubik.className}>
          <div className="mx-auto  h-16 max-w-screen-xl items-center gap-8 px-4 sm:px-6 lg:px-8">
            <Header />
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
